In [133]:
import pandas as pd
import sqlite3
from sqlite3 import Error
from pathlib import Path
from sqlalchemy import create_engine
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt
import numpy as np

In [134]:
#import the csv files
optn_csv = "output/optn_remove_agg.csv"

#create dataframe csv
df = pd.read_csv(optn_csv)

In [135]:
df.columns

Index(['Unnamed: 0', 'Age', 'Ethnicities', 'Wait Time', 'Alabama', 'Alaska',
       'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
       'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii',
       'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New_Hampshire', 'New_Jersey', 'New_Mexico', 'New_York',
       'North_Carolina', 'North_Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode_Island', 'South_Carolina', 'South_Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West_Virginia', 'Wisconsin', 'Wyoming'],
      dtype='object')

In [136]:
optn_df = df.drop('Unnamed: 0', axis=1)
optn_df.head()

,Age,Ethnicities,Wait Time,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,...,South_Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West_Virginia,Wisconsin,Wyoming
0,0-5 Years,White alone,< 30 Days,0,1,0,0,6,1,0,...,0,1,4,1,0,0,1,1,2,0
1,0-5 Years,White alone,30 to < 90 Days,1,0,4,2,6,4,1,...,0,0,4,0,0,4,1,3,1,0
2,0-5 Years,White alone,90 Days to < 6 Months,1,0,3,0,7,1,1,...,0,4,5,3,0,3,0,2,1,0
3,0-5 Years,White alone,6 Months to < 1 Year,1,0,0,1,0,3,0,...,0,1,14,0,1,2,0,0,1,0
4,0-5 Years,White alone,1 Year to < 2 Years,0,0,0,0,8,0,0,...,0,0,5,0,1,1,3,0,1,0

In [137]:
#There are 54 columns in this dataframe, Age is the 0 column 
#I need to get the value under the state, the column name for the state, the age, ethnicity, wait time
col_alabama = optn_df.columns[3]
alabama_df = pd.DataFrame(optn_df[['Alabama', 'Age', 'Ethnicities', 'Wait Time']])
alabama_df = alabama_df.rename(columns={'Alabama': 'People'})
alabama_df['State'] = 'Alabama'

In [138]:
#create a loop to get all the state dataframes
for c in range(4, 54):
    col = optn_df.columns[c]
    print(col)
    #above is Alaska
    col_l = col.lower()
    print(col_l)
    #above is lowercase name
    #dataframe name below
    df_name_string = f'{col_l}_df' 
    print(df_name_string)
    #add in the columns I want to get
    df_name = pd.DataFrame(optn_df[[col, 'Age', 'Ethnicities', 'Wait Time']])
    #rename the state to "People" column
    df_name = df_name.rename(columns={col: 'People'})
    #add in the state for every value in that column
    df_name['State'] = col
    #rename the dataframe to reflect the state
    globals()[df_name_string] = pd.DataFrame(df_name)
    df_name.head()

Alaska
alaska
alaska_df
Arizona
arizona
arizona_df
Arkansas
arkansas
arkansas_df
California
california
california_df
Colorado
colorado
colorado_df
Connecticut
connecticut
connecticut_df
Delaware
delaware
delaware_df
District of Columbia
district of columbia
district of columbia_df
Florida
florida
florida_df
Georgia
georgia
georgia_df
Hawaii
hawaii
hawaii_df
Idaho
idaho
idaho_df
Illinois
illinois
illinois_df
Indiana
indiana
indiana_df
Iowa
iowa
iowa_df
Kansas
kansas
kansas_df
Kentucky
kentucky
kentucky_df
Louisiana
louisiana
louisiana_df
Maine
maine
maine_df
Maryland
maryland
maryland_df
Massachusetts
massachusetts
massachusetts_df
Michigan
michigan
michigan_df
Minnesota
minnesota
minnesota_df
Mississippi
mississippi
mississippi_df
Missouri
missouri
missouri_df
Montana
montana
montana_df
Nebraska
nebraska
nebraska_df
Nevada
nevada
nevada_df
New_Hampshire
new_hampshire
new_hampshire_df
New_Jersey
new_jersey
new_jersey_df
New_Mexico
new_mexico
new_mexico_df
New_York
new_york
new_york_df
North_Carolina
north_carolina
north_carolina_df
North_Dakota
north_dakota
north_dakota_df
Ohio
ohio
ohio_df
Oklahoma
oklahoma
oklahoma_df
Oregon
oregon
oregon_df
Pennsylvania
pennsylvania
pennsylvania_df
Rhode_Island
rhode_island
rhode_island_df
South_Carolina
south_carolina
south_carolina_df
South_Dakota
south_dakota
south_dakota_df
Tennessee
tennessee
tennessee_df
Texas
texas
texas_df
Utah
utah
utah_df
Vermont
vermont
vermont_df
Virginia
virginia
virginia_df
Washington
washington
washington_df
West_Virginia
west_virginia
west_virginia_df
Wisconsin
wisconsin
wisconsin_df
Wyoming
wyoming
wyoming_df

In [139]:
%whos DataFrame

Variable                  Type         Data/Info
------------------------------------------------
alabama_df                DataFrame         People           Age<...>n\n[359 rows x 5 columns]
alaska_df                 DataFrame         People           Age<...>n\n[359 rows x 5 columns]
arizona_df                DataFrame         People           Age<...>n\n[359 rows x 5 columns]
arkansas_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
california_df             DataFrame         People           Age<...>n\n[359 rows x 5 columns]
colorado_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
connecticut_df            DataFrame         People           Age<...>n\n[359 rows x 5 columns]
delaware_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
df                        DataFrame         Unnamed: 0          <...>\n[359 rows x 55 columns]
df_name                   DataFrame         People           Age<...>n\n[359 rows x 5 columns]
district of columbia_df   DataFrame         People           Age<...>n\n[359 rows x 5 columns]
florida_df                DataFrame         People           Age<...>n\n[359 rows x 5 columns]
georgia_df                DataFrame         People           Age<...>n\n[359 rows x 5 columns]
hawaii_df                 DataFrame         People           Age<...>n\n[359 rows x 5 columns]
idaho_df                  DataFrame         People           Age<...>n\n[359 rows x 5 columns]
illinois_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
indiana_df                DataFrame         People           Age<...>n\n[359 rows x 5 columns]
iowa_df                   DataFrame         People           Age<...>n\n[359 rows x 5 columns]
kansas_df                 DataFrame         People           Age<...>n\n[359 rows x 5 columns]
kentucky_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
louisiana_df              DataFrame         People           Age<...>n\n[359 rows x 5 columns]
maine_df                  DataFrame         People           Age<...>n\n[359 rows x 5 columns]
maryland_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
massachusetts_df          DataFrame         People           Age<...>n\n[359 rows x 5 columns]
michigan_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
minnesota_df              DataFrame         People           Age<...>n\n[359 rows x 5 columns]
mississippi_df            DataFrame         People           Age<...>n\n[359 rows x 5 columns]
missouri_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
montana_df                DataFrame         People           Age<...>n\n[359 rows x 5 columns]
nebraska_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
nevada_df                 DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new hampshire_df          DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new jersey_df             DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new mexico_df             DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new york_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new_hampshire_df          DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new_jersey_df             DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new_mexico_df             DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new_york_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
north carolina_df         DataFrame         People           Age<...>n\n[359 rows x 5 columns]
north dakota_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
north_carolina_df         DataFrame         People           Age<...>n\n[359 rows x 5 columns]
north_dakota_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
ohio_df                   DataFrame         People           Age<...>n\n[359 rows x 5 columns]
oklahoma_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
optn_df                   DataFrame                  Age        <...>\n[359 rows x 54 columns]
oregon_df                 DataFrame         People           Age<...>n\n[359 rows x 5 columns]
pennsylvania_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
rhode island_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
rhode_island_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
south carolina_df         DataFrame         People           Age<...>n\n[359 rows x 5 columns]
south dakota_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
south_carolina_df         DataFrame         People           Age<...>n\n[359 rows x 5 columns]
south_dakota_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
tennessee_df              DataFrame         People           Age<...>n\n[359 rows x 5 columns]
texas_df                  DataFrame         People           Age<...>n\n[359 rows x 5 columns]
utah_df                   DataFrame         People           Age<...>n\n[359 rows x 5 columns]
vermont_df                DataFrame         People           Age<...>n\n[359 rows x 5 columns]
virginia_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
washington_df             DataFrame         People           Age<...>n\n[359 rows x 5 columns]
west virginia_df          DataFrame         People           Age<...>n\n[359 rows x 5 columns]
west_virginia_df          DataFrame         People           Age<...>n\n[359 rows x 5 columns]
wisconsin_df              DataFrame         People           Age<...>n\n[359 rows x 5 columns]
wyoming_df                DataFrame         People           Age<...>n\n[359 rows x 5 columns]

In [ ]:
# #Arkansas
# col_alaska = optn_df.columns[6]
# arizona_df = pd.DataFrame(optn_df[['Arizona', 'Age', 'Ethnicities', 'Wait Time']])
# arizona_df = alabama_df.rename(columns={'Arizona': 'People'})
# arizona_df['State'] = 'Arizona'

In [140]:
new_hampshire_df.head()

   People        Age  Ethnicities              Wait Time          State
0       0  0-5 Years  White alone              < 30 Days  New_Hampshire
1       0  0-5 Years  White alone        30 to < 90 Days  New_Hampshire
2       1  0-5 Years  White alone  90 Days to < 6 Months  New_Hampshire
3       0  0-5 Years  White alone   6 Months to < 1 Year  New_Hampshire
4       0  0-5 Years  White alone    1 Year to < 2 Years  New_Hampshire

In [141]:
Path('optn_census.db').touch()

In [142]:
#def create_connection()
#create a database connection
conn = sqlite3.connect('optn_census.db')
c = conn.cursor()

In [149]:
alabama_df.to_sql('alabama', conn, if_exists='replace', index=False)
alaska_df.to_sql('alaska', conn, if_exists='replace', index=False)
arizona_df.to_sql('arizona', conn, if_exists='replace', index=False)
arkansas_df.to_sql('arkansas', conn, if_exists='replace', index=False)
california_df.to_sql('california', conn, if_exists='replace', index=False)
colorado_df.to_sql('colorado', conn, if_exists='replace', index=False)
connecticut_df.to_sql('connecticut', conn, if_exists='replace', index=False)
delaware_df.to_sql('delaware', conn, if_exists='replace', index=False)
florida_df.to_sql('florida', conn, if_exists='replace', index=False)
georgia_df.to_sql('georgia', conn, if_exists='replace', index=False)
hawaii_df.to_sql('hawaii', conn, if_exists='replace', index=False)
idaho_df.to_sql('idaho', conn, if_exists='replace', index=False)
illinois_df.to_sql('illinois', conn, if_exists='replace', index=False)
indiana_df.to_sql('indiana', conn, if_exists='replace', index=False)
iowa_df.to_sql('iowa', conn, if_exists='replace', index=False)
kansas_df.to_sql('kansas', conn, if_exists='replace', index=False)
kentucky_df.to_sql('kentucky', conn, if_exists='replace', index=False)
louisiana_df.to_sql('louisiana', conn, if_exists='replace', index=False)
maine_df.to_sql('maine', conn, if_exists='replace', index=False)
maryland_df.to_sql('maryland', conn, if_exists='replace', index=False)
massachusetts_df.to_sql('massachusetts', conn, if_exists='replace', index=False)
michigan_df.to_sql('michigan', conn, if_exists='replace', index=False)
minnesota_df.to_sql('minnesota', conn, if_exists='replace', index=False)
mississippi_df.to_sql('mississippi', conn, if_exists='replace', index=False)
missouri_df.to_sql('missouri', conn, if_exists='replace', index=False)
montana_df.to_sql('montana', conn, if_exists='replace', index=False)
nebraska_df.to_sql('nebraska', conn, if_exists='replace', index=False)
nevada_df.to_sql('nevada', conn, if_exists='replace', index=False)
new_hampshire_df.to_sql('new_hampshire', conn, if_exists='replace', index=False)
new_jersey_df.to_sql('new_jersey', conn, if_exists='replace', index=False)
new_mexico_df.to_sql('new_mexico', conn, if_exists='replace', index=False)
new_york_df.to_sql('new_york', conn, if_exists='replace', index=False)
north_carolina_df.to_sql('north_carolina', conn, if_exists='replace', index=False)
north_dakota_df.to_sql('north_dakota', conn, if_exists='replace', index=False)
ohio_df.to_sql('ohio', conn, if_exists='replace', index=False)
oklahoma_df.to_sql('oklahoma', conn, if_exists='replace', index=False)
oregon_df.to_sql('oregon', conn, if_exists='replace', index=False)
pennsylvania_df.to_sql('pennsylvania', conn, if_exists='replace', index=False)
rhode_island_df.to_sql('rhode_island', conn, if_exists='replace', index=False)
south_carolina_df.to_sql('south_carolina', conn, if_exists='replace', index=False)
south_dakota_df.to_sql('south_dakota', conn, if_exists='replace', index=False)
tennessee_df.to_sql('tennessee', conn, if_exists='replace', index=False)
texas_df.to_sql('texas', conn, if_exists='replace', index=False)
utah_df.to_sql('utah', conn, if_exists='replace', index=False)
vermont_df.to_sql('vermont', conn, if_exists='replace', index=False)
virginia_df.to_sql('virginia', conn, if_exists='replace', index=False)
washington_df.to_sql('washington', conn, if_exists='replace', index=False)
west_virginia_df.to_sql('west_virginia', conn, if_exists='replace', index=False)
wisconsin_df.to_sql('wisconsin', conn, if_exists='replace', index=False)
wyoming_df.to_sql('wyoming_df', conn, if_exists='replace', index=False)

In [150]:
database_path = Path("optn_census.db")
engine = create_engine(f"sqlite:///{database_path}")

In [154]:
data = engine.execute("SELECT * FROM west_virginia")

for record in data:
    print(record)

(1, '0-5 Years', 'White alone', '< 30 Days', 'West_Virginia')
(3, '0-5 Years', 'White alone', '30 to < 90 Days', 'West_Virginia')
(2, '0-5 Years', 'White alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '0-5 Years', 'White alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '0-5 Years', 'White alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '0-5 Years', 'White alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '0-5 Years', 'White alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '0-5 Years', 'White alone', '5 or More Years', 'West_Virginia')
(0, '0-5 Years', 'Black or African American alone', '< 30 Days', 'West_Virginia')
(0, '0-5 Years', 'Black or African American alone', '30 to < 90 Days', 'West_Virginia')
(0, '0-5 Years', 'Black or African American alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '0-5 Years', 'Black or African American alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '0-5 Years', 'Black or African American alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '0-5 Years', 'Black or African American alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '0-5 Years', 'Black or African American alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '0-5 Years', 'Hispanic or Latino', '< 30 Days', 'West_Virginia')
(0, '0-5 Years', 'Hispanic or Latino', '30 to < 90 Days', 'West_Virginia')
(0, '0-5 Years', 'Hispanic or Latino', '90 Days to < 6 Months', 'West_Virginia')
(0, '0-5 Years', 'Hispanic or Latino', '6 Months to < 1 Year', 'West_Virginia')
(0, '0-5 Years', 'Hispanic or Latino', '1 Year to < 2 Years', 'West_Virginia')
(0, '0-5 Years', 'Hispanic or Latino', '2 Years to < 3 Years', 'West_Virginia')
(0, '0-5 Years', 'Hispanic or Latino', '3 Years to < 5 Years', 'West_Virginia')
(0, '0-5 Years', 'Hispanic or Latino', '5 or More Years', 'West_Virginia')
(0, '0-5 Years', 'Asian alone', '< 30 Days', 'West_Virginia')
(0, '0-5 Years', 'Asian alone', '30 to < 90 Days', 'West_Virginia')
(0, '0-5 Years', 'Asian alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '0-5 Years', 'Asian alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '0-5 Years', 'Asian alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '0-5 Years', 'Asian alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '0-5 Years', 'Asian alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '0-5 Years', 'American Indian and Alaska Native alone', '< 30 Days', 'West_Virginia')
(0, '0-5 Years', 'American Indian and Alaska Native alone', '30 to < 90 Days', 'West_Virginia')
(0, '0-5 Years', 'American Indian and Alaska Native alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '0-5 Years', 'American Indian and Alaska Native alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '0-5 Years', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '0-5 Years', 'Native Hawaiian and Other Pacific Islander alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '0-5 Years', 'Native Hawaiian and Other Pacific Islander alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '0-5 Years', 'Population of two or more races:', '< 30 Days', 'West_Virginia')
(0, '0-5 Years', 'Population of two or more races:', '30 to < 90 Days', 'West_Virginia')
(0, '0-5 Years', 'Population of two or more races:', '90 Days to < 6 Months', 'West_Virginia')
(0, '0-5 Years', 'Population of two or more races:', '6 Months to < 1 Year', 'West_Virginia')
(0, '0-5 Years', 'Population of two or more races:', '1 Year to < 2 Years', 'West_Virginia')
(0, '0-5 Years', 'Population of two or more races:', '2 Years to < 3 Years', 'West_Virginia')
(0, '6-10 Years', 'White alone', '< 30 Days', 'West_Virginia')
(0, '6-10 Years', 'White alone', '30 to < 90 Days', 'West_Virginia')
(0, '6-10 Years', 'White alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '6-10 Years', 'White alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '6-10 Years', 'White alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '6-10 Years', 'White alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '6-10 Years', 'White alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '6-10 Years', 'White alone', '5 or More Years', 'West_Virginia')
(0, '6-10 Years', 'Black or African American alone', '< 30 Days', 'West_Virginia')
(0, '6-10 Years', 'Black or African American alone', '30 to < 90 Days', 'West_Virginia')
(0, '6-10 Years', 'Black or African American alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '6-10 Years', 'Black or African American alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '6-10 Years', 'Black or African American alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '6-10 Years', 'Black or African American alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '6-10 Years', 'Black or African American alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '6-10 Years', 'Black or African American alone', '5 or More Years', 'West_Virginia')
(0, '6-10 Years', 'Hispanic or Latino', '< 30 Days', 'West_Virginia')
(0, '6-10 Years', 'Hispanic or Latino', '30 to < 90 Days', 'West_Virginia')
(0, '6-10 Years', 'Hispanic or Latino', '90 Days to < 6 Months', 'West_Virginia')
(0, '6-10 Years', 'Hispanic or Latino', '6 Months to < 1 Year', 'West_Virginia')
(0, '6-10 Years', 'Hispanic or Latino', '1 Year to < 2 Years', 'West_Virginia')
(0, '6-10 Years', 'Hispanic or Latino', '2 Years to < 3 Years', 'West_Virginia')
(0, '6-10 Years', 'Hispanic or Latino', '3 Years to < 5 Years', 'West_Virginia')
(0, '6-10 Years', 'Hispanic or Latino', '5 or More Years', 'West_Virginia')
(0, '6-10 Years', 'Asian alone', '< 30 Days', 'West_Virginia')
(0, '6-10 Years', 'Asian alone', '30 to < 90 Days', 'West_Virginia')
(0, '6-10 Years', 'Asian alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '6-10 Years', 'Asian alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '6-10 Years', 'Asian alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '6-10 Years', 'Asian alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '6-10 Years', 'Asian alone', '5 or More Years', 'West_Virginia')
(0, '6-10 Years', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '6-10 Years', 'American Indian and Alaska Native alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '6-10 Years', 'Native Hawaiian and Other Pacific Islander alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '6-10 Years', 'Native Hawaiian and Other Pacific Islander alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '6-10 Years', 'Native Hawaiian and Other Pacific Islander alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '6-10 Years', 'Population of two or more races:', '< 30 Days', 'West_Virginia')
(0, '6-10 Years', 'Population of two or more races:', '90 Days to < 6 Months', 'West_Virginia')
(0, '6-10 Years', 'Population of two or more races:', '6 Months to < 1 Year', 'West_Virginia')
(0, '6-10 Years', 'Population of two or more races:', '1 Year to < 2 Years', 'West_Virginia')
(0, '6-10 Years', 'Population of two or more races:', '2 Years to < 3 Years', 'West_Virginia')
(0, '6-10 Years', 'Population of two or more races:', '3 Years to < 5 Years', 'West_Virginia')
(0, '6-10 Years', 'Population of two or more races:', '5 or More Years', 'West_Virginia')
(0, '11-17 Years', 'White alone', '< 30 Days', 'West_Virginia')
(0, '11-17 Years', 'White alone', '30 to < 90 Days', 'West_Virginia')
(5, '11-17 Years', 'White alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '11-17 Years', 'White alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '11-17 Years', 'White alone', '1 Year to < 2 Years', 'West_Virginia')
(1, '11-17 Years', 'White alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '11-17 Years', 'White alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '11-17 Years', 'White alone', '5 or More Years', 'West_Virginia')
(0, '11-17 Years', 'Black or African American alone', '< 30 Days', 'West_Virginia')
(0, '11-17 Years', 'Black or African American alone', '30 to < 90 Days', 'West_Virginia')
(0, '11-17 Years', 'Black or African American alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '11-17 Years', 'Black or African American alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '11-17 Years', 'Black or African American alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '11-17 Years', 'Black or African American alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '11-17 Years', 'Black or African American alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '11-17 Years', 'Black or African American alone', '5 or More Years', 'West_Virginia')
(0, '11-17 Years', 'Hispanic or Latino', '< 30 Days', 'West_Virginia')
(0, '11-17 Years', 'Hispanic or Latino', '30 to < 90 Days', 'West_Virginia')
(0, '11-17 Years', 'Hispanic or Latino', '90 Days to < 6 Months', 'West_Virginia')
(0, '11-17 Years', 'Hispanic or Latino', '6 Months to < 1 Year', 'West_Virginia')
(0, '11-17 Years', 'Hispanic or Latino', '1 Year to < 2 Years', 'West_Virginia')
(0, '11-17 Years', 'Hispanic or Latino', '2 Years to < 3 Years', 'West_Virginia')
(0, '11-17 Years', 'Hispanic or Latino', '3 Years to < 5 Years', 'West_Virginia')
(0, '11-17 Years', 'Hispanic or Latino', '5 or More Years', 'West_Virginia')
(0, '11-17 Years', 'Asian alone', '< 30 Days', 'West_Virginia')
(0, '11-17 Years', 'Asian alone', '30 to < 90 Days', 'West_Virginia')
(0, '11-17 Years', 'Asian alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '11-17 Years', 'Asian alone', '6 Months to < 1 Year', 'West_Virginia')
(1, '11-17 Years', 'Asian alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '11-17 Years', 'Asian alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '11-17 Years', 'Asian alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '11-17 Years', 'Asian alone', '5 or More Years', 'West_Virginia')
(0, '11-17 Years', 'American Indian and Alaska Native alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '11-17 Years', 'American Indian and Alaska Native alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '11-17 Years', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '11-17 Years', 'American Indian and Alaska Native alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '11-17 Years', 'American Indian and Alaska Native alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', '30 to < 90 Days', 'West_Virginia')
(0, '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', '5 or More Years', 'West_Virginia')
(0, '11-17 Years', 'Population of two or more races:', '< 30 Days', 'West_Virginia')
(0, '11-17 Years', 'Population of two or more races:', '30 to < 90 Days', 'West_Virginia')
(0, '11-17 Years', 'Population of two or more races:', '90 Days to < 6 Months', 'West_Virginia')
(0, '11-17 Years', 'Population of two or more races:', '6 Months to < 1 Year', 'West_Virginia')
(1, '11-17 Years', 'Population of two or more races:', '1 Year to < 2 Years', 'West_Virginia')
(0, '11-17 Years', 'Population of two or more races:', '2 Years to < 3 Years', 'West_Virginia')
(0, '11-17 Years', 'Population of two or more races:', '3 Years to < 5 Years', 'West_Virginia')
(0, '11-17 Years', 'Population of two or more races:', '5 or More Years', 'West_Virginia')
(3, '18-34 Years', 'White alone', '< 30 Days', 'West_Virginia')
(3, '18-34 Years', 'White alone', '30 to < 90 Days', 'West_Virginia')
(3, '18-34 Years', 'White alone', '90 Days to < 6 Months', 'West_Virginia')
(9, '18-34 Years', 'White alone', '6 Months to < 1 Year', 'West_Virginia')
(1, '18-34 Years', 'White alone', '1 Year to < 2 Years', 'West_Virginia')
(2, '18-34 Years', 'White alone', '2 Years to < 3 Years', 'West_Virginia')
(2, '18-34 Years', 'White alone', '3 Years to < 5 Years', 'West_Virginia')
(1, '18-34 Years', 'White alone', '5 or More Years', 'West_Virginia')
(0, '18-34 Years', 'Black or African American alone', '< 30 Days', 'West_Virginia')
(1, '18-34 Years', 'Black or African American alone', '30 to < 90 Days', 'West_Virginia')
(1, '18-34 Years', 'Black or African American alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '18-34 Years', 'Black or African American alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '18-34 Years', 'Black or African American alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '18-34 Years', 'Black or African American alone', '2 Years to < 3 Years', 'West_Virginia')
(2, '18-34 Years', 'Black or African American alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '18-34 Years', 'Black or African American alone', '5 or More Years', 'West_Virginia')
(0, '18-34 Years', 'Hispanic or Latino', '< 30 Days', 'West_Virginia')
(0, '18-34 Years', 'Hispanic or Latino', '30 to < 90 Days', 'West_Virginia')
(0, '18-34 Years', 'Hispanic or Latino', '90 Days to < 6 Months', 'West_Virginia')
(0, '18-34 Years', 'Hispanic or Latino', '6 Months to < 1 Year', 'West_Virginia')
(0, '18-34 Years', 'Hispanic or Latino', '1 Year to < 2 Years', 'West_Virginia')
(0, '18-34 Years', 'Hispanic or Latino', '2 Years to < 3 Years', 'West_Virginia')
(0, '18-34 Years', 'Hispanic or Latino', '3 Years to < 5 Years', 'West_Virginia')
(0, '18-34 Years', 'Hispanic or Latino', '5 or More Years', 'West_Virginia')
(0, '18-34 Years', 'Asian alone', '< 30 Days', 'West_Virginia')
(0, '18-34 Years', 'Asian alone', '30 to < 90 Days', 'West_Virginia')
(0, '18-34 Years', 'Asian alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '18-34 Years', 'Asian alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '18-34 Years', 'Asian alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '18-34 Years', 'Asian alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '18-34 Years', 'Asian alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '18-34 Years', 'Asian alone', '5 or More Years', 'West_Virginia')
(0, '18-34 Years', 'American Indian and Alaska Native alone', '< 30 Days', 'West_Virginia')
(0, '18-34 Years', 'American Indian and Alaska Native alone', '30 to < 90 Days', 'West_Virginia')
(0, '18-34 Years', 'American Indian and Alaska Native alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '18-34 Years', 'American Indian and Alaska Native alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '18-34 Years', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '18-34 Years', 'American Indian and Alaska Native alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '18-34 Years', 'American Indian and Alaska Native alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '18-34 Years', 'American Indian and Alaska Native alone', '5 or More Years', 'West_Virginia')
(0, '18-34 Years', 'Native Hawaiian and Other Pacific Islander alone', '< 30 Days', 'West_Virginia')
(0, '18-34 Years', 'Native Hawaiian and Other Pacific Islander alone', '30 to < 90 Days', 'West_Virginia')
(0, '18-34 Years', 'Native Hawaiian and Other Pacific Islander alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '18-34 Years', 'Native Hawaiian and Other Pacific Islander alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '18-34 Years', 'Native Hawaiian and Other Pacific Islander alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '18-34 Years', 'Native Hawaiian and Other Pacific Islander alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '18-34 Years', 'Native Hawaiian and Other Pacific Islander alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '18-34 Years', 'Native Hawaiian and Other Pacific Islander alone', '5 or More Years', 'West_Virginia')
(0, '18-34 Years', 'Population of two or more races:', '< 30 Days', 'West_Virginia')
(0, '18-34 Years', 'Population of two or more races:', '30 to < 90 Days', 'West_Virginia')
(0, '18-34 Years', 'Population of two or more races:', '90 Days to < 6 Months', 'West_Virginia')
(0, '18-34 Years', 'Population of two or more races:', '6 Months to < 1 Year', 'West_Virginia')
(0, '18-34 Years', 'Population of two or more races:', '1 Year to < 2 Years', 'West_Virginia')
(0, '18-34 Years', 'Population of two or more races:', '2 Years to < 3 Years', 'West_Virginia')
(0, '18-34 Years', 'Population of two or more races:', '3 Years to < 5 Years', 'West_Virginia')
(0, '18-34 Years', 'Population of two or more races:', '5 or More Years', 'West_Virginia')
(5, '35-49 Years', 'White alone', '< 30 Days', 'West_Virginia')
(4, '35-49 Years', 'White alone', '30 to < 90 Days', 'West_Virginia')
(14, '35-49 Years', 'White alone', '90 Days to < 6 Months', 'West_Virginia')
(22, '35-49 Years', 'White alone', '6 Months to < 1 Year', 'West_Virginia')
(15, '35-49 Years', 'White alone', '1 Year to < 2 Years', 'West_Virginia')
(13, '35-49 Years', 'White alone', '2 Years to < 3 Years', 'West_Virginia')
(8, '35-49 Years', 'White alone', '3 Years to < 5 Years', 'West_Virginia')
(1, '35-49 Years', 'White alone', '5 or More Years', 'West_Virginia')
(1, '35-49 Years', 'Black or African American alone', '< 30 Days', 'West_Virginia')
(4, '35-49 Years', 'Black or African American alone', '30 to < 90 Days', 'West_Virginia')
(1, '35-49 Years', 'Black or African American alone', '90 Days to < 6 Months', 'West_Virginia')
(5, '35-49 Years', 'Black or African American alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '35-49 Years', 'Black or African American alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '35-49 Years', 'Black or African American alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '35-49 Years', 'Black or African American alone', '3 Years to < 5 Years', 'West_Virginia')
(1, '35-49 Years', 'Black or African American alone', '5 or More Years', 'West_Virginia')
(0, '35-49 Years', 'Hispanic or Latino', '< 30 Days', 'West_Virginia')
(0, '35-49 Years', 'Hispanic or Latino', '30 to < 90 Days', 'West_Virginia')
(0, '35-49 Years', 'Hispanic or Latino', '90 Days to < 6 Months', 'West_Virginia')
(0, '35-49 Years', 'Hispanic or Latino', '6 Months to < 1 Year', 'West_Virginia')
(0, '35-49 Years', 'Hispanic or Latino', '1 Year to < 2 Years', 'West_Virginia')
(0, '35-49 Years', 'Hispanic or Latino', '2 Years to < 3 Years', 'West_Virginia')
(0, '35-49 Years', 'Hispanic or Latino', '3 Years to < 5 Years', 'West_Virginia')
(0, '35-49 Years', 'Hispanic or Latino', '5 or More Years', 'West_Virginia')
(0, '35-49 Years', 'Asian alone', '< 30 Days', 'West_Virginia')
(0, '35-49 Years', 'Asian alone', '30 to < 90 Days', 'West_Virginia')
(0, '35-49 Years', 'Asian alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '35-49 Years', 'Asian alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '35-49 Years', 'Asian alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '35-49 Years', 'Asian alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '35-49 Years', 'Asian alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '35-49 Years', 'Asian alone', '5 or More Years', 'West_Virginia')
(0, '35-49 Years', 'American Indian and Alaska Native alone', '< 30 Days', 'West_Virginia')
(0, '35-49 Years', 'American Indian and Alaska Native alone', '30 to < 90 Days', 'West_Virginia')
(0, '35-49 Years', 'American Indian and Alaska Native alone', '90 Days to < 6 Months', 'West_Virginia')
(0, '35-49 Years', 'American Indian and Alaska Native alone', '6 Months to < 1 Year', 'West_Virginia')
(0, '35-49 Years', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'West_Virginia')
(0, '35-49 Years', 'American Indian and Alaska Native alone', '2 Years to < 3 Years', 'West_Virginia')
(0, '35-49 Years', 'American Indian and Alaska Native alone', '3 Years to < 5 Years', 'West_Virginia')
(0, '35-49 Years', 'American Indian and Alaska Native alone', '5 or More Years', 'West_Virginia')
(0, '35-49 Years', 'Native Hawaiian and Other Pacific Islander alone', '< 30 Days', 'West_Virginia')
(0, '35-49 Years', 'Native Hawaiian and Other Pacific Islander alone', '30 to < 90 Days', 'West_Virginia')

In [155]:
conn.commit()
conn.close()