In [311]:
import pandas as pd
import sqlite3
from sqlite3 import Error
from pathlib import Path
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt
import numpy as np

In [312]:
#import the csv files

optn_csv = "output/optn_clean.csv"
#create dataframe csv
df = pd.read_csv(optn_csv)

In [313]:
df.columns

Index(['Unnamed: 0', 'Age', 'Ethnicities', 'Wait Time', 'Alabama', 'Alaska',
       'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
       'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii',
       'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New_Hampshire', 'New_Jersey', 'New_Mexico', 'New_York',
       'North_Carolina', 'North_Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode_Island', 'South_Carolina', 'South_Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West_Virginia', 'Wisconsin', 'Wyoming'],
      dtype='object')

In [314]:
optn_df = df.drop('Unnamed: 0', axis=1)
optn_df.columns

Index(['Age', 'Ethnicities', 'Wait Time', 'Alabama', 'Alaska', 'Arizona',
       'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New_Hampshire', 'New_Jersey', 'New_Mexico', 'New_York',
       'North_Carolina', 'North_Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode_Island', 'South_Carolina', 'South_Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West_Virginia', 'Wisconsin', 'Wyoming'],
      dtype='object')

In [315]:
#There are 54 columns in this dataframe, Age is the 0 column 
#I need to get the value under the state, the column name for the state, the age, ethnicity, wait time
col_alabama = optn_df.columns[3]
alabama_df = pd.DataFrame(optn_df[['Alabama', 'Age', 'Ethnicities', 'Wait Time']])
alabama_df = alabama_df.rename(columns={'Alabama': 'People'})
alabama_df['State'] = 'Alabama'

In [316]:
#create a loop to get all the state dataframes
for c in range(4, 54):
    col = optn_df.columns[c]
    print(col)
    #above is Alaska
    #col_l = col.lower()
    #print(col_l)
    #above is lowercase name
    #dataframe name below
    #df_name_string = f'{col_l}_df'
    df_name_string = f'{col}_df' 
    print(df_name_string)
    #add in the columns I want to get
    df_name = pd.DataFrame(optn_df[[col, 'Age', 'Ethnicities', 'Wait Time']])
    #rename the state to "People" column
    df_name = df_name.rename(columns={col: 'People'})
    #add in the state for every value in that column
    df_name['State'] = col
    #rename the dataframe to reflect the state
    globals()[df_name_string] = pd.DataFrame(df_name)
    df_name.head()

Alaska
Alaska_df
Arizona
Arizona_df
Arkansas
Arkansas_df
California
California_df
Colorado
Colorado_df
Connecticut
Connecticut_df
Delaware
Delaware_df
District of Columbia
District of Columbia_df
Florida
Florida_df
Georgia
Georgia_df
Hawaii
Hawaii_df
Idaho
Idaho_df
Illinois
Illinois_df
Indiana
Indiana_df
Iowa
Iowa_df
Kansas
Kansas_df
Kentucky
Kentucky_df
Louisiana
Louisiana_df
Maine
Maine_df
Maryland
Maryland_df
Massachusetts
Massachusetts_df
Michigan
Michigan_df
Minnesota
Minnesota_df
Mississippi
Mississippi_df
Missouri
Missouri_df
Montana
Montana_df
Nebraska
Nebraska_df
Nevada
Nevada_df
New_Hampshire
New_Hampshire_df
New_Jersey
New_Jersey_df
New_Mexico
New_Mexico_df
New_York
New_York_df
North_Carolina
North_Carolina_df
North_Dakota
North_Dakota_df
Ohio
Ohio_df
Oklahoma
Oklahoma_df
Oregon
Oregon_df
Pennsylvania
Pennsylvania_df
Rhode_Island
Rhode_Island_df
South_Carolina
South_Carolina_df
South_Dakota
South_Dakota_df
Tennessee
Tennessee_df
Texas
Texas_df
Utah
Utah_df
Vermont
Vermont_df
Virginia
Virginia_df
Washington
Washington_df
West_Virginia
West_Virginia_df
Wisconsin
Wisconsin_df
Wyoming
Wyoming_df

In [317]:
#list the dataframes. Leaving out district of columbia
%whos DataFrame

Variable                  Type         Data/Info
------------------------------------------------
Alaska_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Arizona_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Arkansas_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
California_df             DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Colorado_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Connecticut_df            DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Delaware_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
District of Columbia_df   DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Florida_df                DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Georgia_df                DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Hawaii_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Idaho_df                  DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Illinois_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Indiana_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Iowa_df                   DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Kansas_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Kentucky_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Louisiana_df              DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Maine_df                  DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Maryland_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Massachusetts_df          DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Michigan_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Minnesota_df              DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Mississippi_df            DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Missouri_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Montana_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Nebraska_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Nevada_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
New_Hampshire_df          DataFrame         People           Age<...>n\n[471 rows x 5 columns]
New_Jersey_df             DataFrame        People           Age <...>n\n[471 rows x 5 columns]
New_Mexico_df             DataFrame         People           Age<...>n\n[471 rows x 5 columns]
New_York_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
North_Carolina_df         DataFrame        People           Age <...>n\n[471 rows x 5 columns]
North_Dakota_df           DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Ohio_df                   DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Oklahoma_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Oregon_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Pennsylvania_df           DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Rhode_Island_df           DataFrame         People           Age<...>n\n[471 rows x 5 columns]
South_Carolina_df         DataFrame        People           Age <...>n\n[471 rows x 5 columns]
South_Dakota_df           DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Tennessee_df              DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Texas_df                  DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Utah_df                   DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Vermont_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Virginia_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Washington_df             DataFrame         People           Age<...>n\n[471 rows x 5 columns]
West_Virginia_df          DataFrame         People           Age<...>n\n[471 rows x 5 columns]
Wisconsin_df              DataFrame        People           Age <...>n\n[471 rows x 5 columns]
Wyoming_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
age_ethnicity_state       DataFrame        Unnamed: 0           <...>n\n[64 rows x 56 columns]
age_waittime_state        DataFrame        Unnamed: 0           <...>n\n[72 rows x 56 columns]
alabama_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
alaska_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
arizona_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
arkansas_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
california_df             DataFrame        People           Age <...>n\n[471 rows x 5 columns]
census_age                DataFrame                Age United St<...>\n\n[8 rows x 53 columns]
census_age_percent        DataFrame       Unnamed: 0           A<...>\n\n[7 rows x 54 columns]
census_eth_df_percent     DataFrame       Unnamed: 0            <...>\n\n[8 rows x 54 columns]
census_ethn               DataFrame                             <...>\n\n[9 rows x 53 columns]
colorado_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
connecticut_df            DataFrame         People           Age<...>n\n[471 rows x 5 columns]
delaware_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
df                        DataFrame         Unnamed: 0          <...>\n[471 rows x 55 columns]
df_name                   DataFrame         People           Age<...>n\n[471 rows x 5 columns]
district of columbia_df   DataFrame         People           Age<...>n\n[471 rows x 5 columns]
florida_df                DataFrame        People           Age <...>n\n[471 rows x 5 columns]
georgia_df                DataFrame        People           Age <...>n\n[471 rows x 5 columns]
hawaii_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
idaho_df                  DataFrame         People           Age<...>n\n[471 rows x 5 columns]
illinois_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
indiana_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
iowa_df                   DataFrame         People           Age<...>n\n[471 rows x 5 columns]
kansas_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
kentucky_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
louisiana_df              DataFrame        People           Age <...>n\n[471 rows x 5 columns]
maine_df                  DataFrame         People           Age<...>n\n[471 rows x 5 columns]
maryland_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
massachusetts_df          DataFrame        People           Age <...>n\n[471 rows x 5 columns]
michigan_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
minnesota_df              DataFrame        People           Age <...>n\n[471 rows x 5 columns]
mississippi_df            DataFrame         People           Age<...>n\n[471 rows x 5 columns]
missouri_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
montana_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
nebraska_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
nevada_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
new hampshire_df          DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new jersey_df             DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new mexico_df             DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new york_df               DataFrame         People           Age<...>n\n[359 rows x 5 columns]
new_hampshire_df          DataFrame         People           Age<...>n\n[471 rows x 5 columns]
new_jersey_df             DataFrame        People           Age <...>n\n[471 rows x 5 columns]
new_mexico_df             DataFrame         People           Age<...>n\n[471 rows x 5 columns]
new_york_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
north carolina_df         DataFrame         People           Age<...>n\n[359 rows x 5 columns]
north dakota_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
north_carolina_df         DataFrame        People           Age <...>n\n[471 rows x 5 columns]
north_dakota_df           DataFrame         People           Age<...>n\n[471 rows x 5 columns]
ohio_df                   DataFrame        People           Age <...>n\n[471 rows x 5 columns]
oklahoma_df               DataFrame         People           Age<...>n\n[471 rows x 5 columns]
optn_df                   DataFrame                  Age        <...>\n[471 rows x 54 columns]
oregon_df                 DataFrame         People           Age<...>n\n[471 rows x 5 columns]
pennsylvania_df           DataFrame        People           Age <...>n\n[471 rows x 5 columns]
rhode island_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
rhode_island_df           DataFrame         People           Age<...>n\n[471 rows x 5 columns]
south carolina_df         DataFrame         People           Age<...>n\n[359 rows x 5 columns]

south dakota_df           DataFrame         People           Age<...>n\n[359 rows x 5 columns]
south_carolina_df         DataFrame        People           Age <...>n\n[471 rows x 5 columns]
south_dakota_df           DataFrame         People           Age<...>n\n[471 rows x 5 columns]
tennessee_df              DataFrame        People           Age <...>n\n[471 rows x 5 columns]
texas_df                  DataFrame        People           Age <...>n\n[471 rows x 5 columns]
utah_df                   DataFrame         People           Age<...>n\n[471 rows x 5 columns]
vermont_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]
virginia_df               DataFrame        People           Age <...>n\n[471 rows x 5 columns]
washington_df             DataFrame         People           Age<...>n\n[471 rows x 5 columns]
west virginia_df          DataFrame         People           Age<...>n\n[359 rows x 5 columns]
west_virginia_df          DataFrame         People           Age<...>n\n[471 rows x 5 columns]
wisconsin_df              DataFrame        People           Age <...>n\n[471 rows x 5 columns]
wyoming_df                DataFrame         People           Age<...>n\n[471 rows x 5 columns]

In [318]:
#check a dataframe
alabama_df.head(10)

,People,Age,Ethnicities,Wait Time,State
0,681,All Ages,White alone,All Time,Alabama
1,25,All Ages,White alone,< 30 Days,Alabama
2,49,All Ages,White alone,30 to < 90 Days,Alabama
3,71,All Ages,White alone,90 Days to < 6 Months,Alabama
4,159,All Ages,White alone,6 Months to < 1 Year,Alabama
5,177,All Ages,White alone,1 Year to < 2 Years,Alabama
6,95,All Ages,White alone,2 Years to < 3 Years,Alabama
7,80,All Ages,White alone,3 Years to < 5 Years,Alabama
8,25,All Ages,White alone,5 or More Years,Alabama
9,904,All Ages,Black or African American alone,All Time,Alabama

In [319]:
california_df.to_csv('output/california.csv')

In [320]:
#create the database
Path('optn_census.db').touch()

In [321]:
#create a database connection
conn = sqlite3.connect('optn_census.db')
c = conn.cursor()

In [322]:
alabama_df.to_sql('alabama', conn, if_exists='replace', index=False)
alaska_df.to_sql('alaska', conn, if_exists='replace', index=False)
arizona_df.to_sql('arizona', conn, if_exists='replace', index=False)
arkansas_df.to_sql('arkansas', conn, if_exists='replace', index=False)
california_df.to_sql('california', conn, if_exists='replace', index=False)
colorado_df.to_sql('colorado', conn, if_exists='replace', index=False)
connecticut_df.to_sql('connecticut', conn, if_exists='replace', index=False)
delaware_df.to_sql('delaware', conn, if_exists='replace', index=False)
florida_df.to_sql('florida', conn, if_exists='replace', index=False)
georgia_df.to_sql('georgia', conn, if_exists='replace', index=False)
hawaii_df.to_sql('hawaii', conn, if_exists='replace', index=False)
idaho_df.to_sql('idaho', conn, if_exists='replace', index=False)
illinois_df.to_sql('illinois', conn, if_exists='replace', index=False)
indiana_df.to_sql('indiana', conn, if_exists='replace', index=False)
iowa_df.to_sql('iowa', conn, if_exists='replace', index=False)
kansas_df.to_sql('kansas', conn, if_exists='replace', index=False)
kentucky_df.to_sql('kentucky', conn, if_exists='replace', index=False)
louisiana_df.to_sql('louisiana', conn, if_exists='replace', index=False)
maine_df.to_sql('maine', conn, if_exists='replace', index=False)
maryland_df.to_sql('maryland', conn, if_exists='replace', index=False)
massachusetts_df.to_sql('massachusetts', conn, if_exists='replace', index=False)
michigan_df.to_sql('michigan', conn, if_exists='replace', index=False)
minnesota_df.to_sql('minnesota', conn, if_exists='replace', index=False)
mississippi_df.to_sql('mississippi', conn, if_exists='replace', index=False)
missouri_df.to_sql('missouri', conn, if_exists='replace', index=False)
montana_df.to_sql('montana', conn, if_exists='replace', index=False)
nebraska_df.to_sql('nebraska', conn, if_exists='replace', index=False)
nevada_df.to_sql('nevada', conn, if_exists='replace', index=False)
new_hampshire_df.to_sql('new_hampshire', conn, if_exists='replace', index=False)
new_jersey_df.to_sql('new_jersey', conn, if_exists='replace', index=False)
new_mexico_df.to_sql('new_mexico', conn, if_exists='replace', index=False)
new_york_df.to_sql('new_york', conn, if_exists='replace', index=False)
north_carolina_df.to_sql('north_carolina', conn, if_exists='replace', index=False)
north_dakota_df.to_sql('north_dakota', conn, if_exists='replace', index=False)
ohio_df.to_sql('ohio', conn, if_exists='replace', index=False)
oklahoma_df.to_sql('oklahoma', conn, if_exists='replace', index=False)
oregon_df.to_sql('oregon', conn, if_exists='replace', index=False)
pennsylvania_df.to_sql('pennsylvania', conn, if_exists='replace', index=False)
rhode_island_df.to_sql('rhode_island', conn, if_exists='replace', index=False)
south_carolina_df.to_sql('south_carolina', conn, if_exists='replace', index=False)
south_dakota_df.to_sql('south_dakota', conn, if_exists='replace', index=False)
tennessee_df.to_sql('tennessee', conn, if_exists='replace', index=False)
texas_df.to_sql('texas', conn, if_exists='replace', index=False)
utah_df.to_sql('utah', conn, if_exists='replace', index=False)
vermont_df.to_sql('vermont', conn, if_exists='replace', index=False)
virginia_df.to_sql('virginia', conn, if_exists='replace', index=False)
washington_df.to_sql('washington', conn, if_exists='replace', index=False)
west_virginia_df.to_sql('west_virginia', conn, if_exists='replace', index=False)
wisconsin_df.to_sql('wisconsin', conn, if_exists='replace', index=False)
wyoming_df.to_sql('wyoming', conn, if_exists='replace', index=False)

/Users/kathleen/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pandas/core/generic.py:2882: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,

In [323]:
data = c.execute("SELECT * FROM pennsylvania")

for record in data:
    print(record)

('2,772', 'All Ages', 'White alone', 'All Time', 'Pennsylvania')
('109', 'All Ages', 'White alone', '< 30 Days', 'Pennsylvania')
('254', 'All Ages', 'White alone', '30 to < 90 Days', 'Pennsylvania')
('270', 'All Ages', 'White alone', '90 Days to < 6 Months', 'Pennsylvania')
('491', 'All Ages', 'White alone', '6 Months to < 1 Year', 'Pennsylvania')
('598', 'All Ages', 'White alone', '1 Year to < 2 Years', 'Pennsylvania')
('349', 'All Ages', 'White alone', '2 Years to < 3 Years', 'Pennsylvania')
('430', 'All Ages', 'White alone', '3 Years to < 5 Years', 'Pennsylvania')
('271', 'All Ages', 'White alone', '5 or More Years', 'Pennsylvania')
('1,844', 'All Ages', 'Black or African American alone', 'All Time', 'Pennsylvania')
('55', 'All Ages', 'Black or African American alone', '< 30 Days', 'Pennsylvania')
('109', 'All Ages', 'Black or African American alone', '30 to < 90 Days', 'Pennsylvania')
('133', 'All Ages', 'Black or African American alone', '90 Days to < 6 Months', 'Pennsylvania')
('241', 'All Ages', 'Black or African American alone', '6 Months to < 1 Year', 'Pennsylvania')
('413', 'All Ages', 'Black or African American alone', '1 Year to < 2 Years', 'Pennsylvania')
('227', 'All Ages', 'Black or African American alone', '2 Years to < 3 Years', 'Pennsylvania')
('366', 'All Ages', 'Black or African American alone', '3 Years to < 5 Years', 'Pennsylvania')
('300', 'All Ages', 'Black or African American alone', '5 or More Years', 'Pennsylvania')
('422', 'All Ages', 'Hispanic or Latino', 'All Time', 'Pennsylvania')
('13', 'All Ages', 'Hispanic or Latino', '< 30 Days', 'Pennsylvania')
('29', 'All Ages', 'Hispanic or Latino', '30 to < 90 Days', 'Pennsylvania')
('34', 'All Ages', 'Hispanic or Latino', '90 Days to < 6 Months', 'Pennsylvania')
('77', 'All Ages', 'Hispanic or Latino', '6 Months to < 1 Year', 'Pennsylvania')
('90', 'All Ages', 'Hispanic or Latino', '1 Year to < 2 Years', 'Pennsylvania')
('69', 'All Ages', 'Hispanic or Latino', '2 Years to < 3 Years', 'Pennsylvania')
('69', 'All Ages', 'Hispanic or Latino', '3 Years to < 5 Years', 'Pennsylvania')
('41', 'All Ages', 'Hispanic or Latino', '5 or More Years', 'Pennsylvania')
('245', 'All Ages', 'Asian alone', 'All Time', 'Pennsylvania')
('6', 'All Ages', 'Asian alone', '< 30 Days', 'Pennsylvania')
('17', 'All Ages', 'Asian alone', '30 to < 90 Days', 'Pennsylvania')
('28', 'All Ages', 'Asian alone', '90 Days to < 6 Months', 'Pennsylvania')
('26', 'All Ages', 'Asian alone', '6 Months to < 1 Year', 'Pennsylvania')
('65', 'All Ages', 'Asian alone', '1 Year to < 2 Years', 'Pennsylvania')
('22', 'All Ages', 'Asian alone', '2 Years to < 3 Years', 'Pennsylvania')
('57', 'All Ages', 'Asian alone', '3 Years to < 5 Years', 'Pennsylvania')
('24', 'All Ages', 'Asian alone', '5 or More Years', 'Pennsylvania')
('8', 'All Ages', 'American Indian and Alaska Native alone', 'All Time', 'Pennsylvania')
('0', 'All Ages', 'American Indian and Alaska Native alone', '< 30 Days', 'Pennsylvania')
('0', 'All Ages', 'American Indian and Alaska Native alone', '30 to < 90 Days', 'Pennsylvania')
('1', 'All Ages', 'American Indian and Alaska Native alone', '90 Days to < 6 Months', 'Pennsylvania')
('3', 'All Ages', 'American Indian and Alaska Native alone', '6 Months to < 1 Year', 'Pennsylvania')
('2', 'All Ages', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', 'All Ages', 'American Indian and Alaska Native alone', '2 Years to < 3 Years', 'Pennsylvania')
('2', 'All Ages', 'American Indian and Alaska Native alone', '3 Years to < 5 Years', 'Pennsylvania')
('0', 'All Ages', 'American Indian and Alaska Native alone', '5 or More Years', 'Pennsylvania')
('2', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', 'All Time', 'Pennsylvania')
('0', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', '< 30 Days', 'Pennsylvania')
('1', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', '30 to < 90 Days', 'Pennsylvania')
('0', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', '90 Days to < 6 Months', 'Pennsylvania')
('0', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', '6 Months to < 1 Year', 'Pennsylvania')
('0', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', '2 Years to < 3 Years', 'Pennsylvania')
('0', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', '3 Years to < 5 Years', 'Pennsylvania')
('1', 'All Ages', 'Native Hawaiian and Other Pacific Islander alone', '5 or More Years', 'Pennsylvania')
('23', 'All Ages', 'Population of two or more races:', 'All Time', 'Pennsylvania')
('0', 'All Ages', 'Population of two or more races:', '< 30 Days', 'Pennsylvania')
('4', 'All Ages', 'Population of two or more races:', '30 to < 90 Days', 'Pennsylvania')
('2', 'All Ages', 'Population of two or more races:', '90 Days to < 6 Months', 'Pennsylvania')
('3', 'All Ages', 'Population of two or more races:', '6 Months to < 1 Year', 'Pennsylvania')
('0', 'All Ages', 'Population of two or more races:', '1 Year to < 2 Years', 'Pennsylvania')
('4', 'All Ages', 'Population of two or more races:', '2 Years to < 3 Years', 'Pennsylvania')
('5', 'All Ages', 'Population of two or more races:', '3 Years to < 5 Years', 'Pennsylvania')
('5', 'All Ages', 'Population of two or more races:', '5 or More Years', 'Pennsylvania')
('12', '0-5 Years', 'White alone', 'All Time', 'Pennsylvania')
('0', '0-5 Years', 'White alone', '< 30 Days', 'Pennsylvania')
('3', '0-5 Years', 'White alone', '30 to < 90 Days', 'Pennsylvania')
('2', '0-5 Years', 'White alone', '90 Days to < 6 Months', 'Pennsylvania')
('3', '0-5 Years', 'White alone', '6 Months to < 1 Year', 'Pennsylvania')
('3', '0-5 Years', 'White alone', '1 Year to < 2 Years', 'Pennsylvania')
('1', '0-5 Years', 'White alone', '2 Years to < 3 Years', 'Pennsylvania')
('0', '0-5 Years', 'White alone', '3 Years to < 5 Years', 'Pennsylvania')
('0', '0-5 Years', 'White alone', '5 or More Years', 'Pennsylvania')
('2', '0-5 Years', 'Black or African American alone', 'All Time', 'Pennsylvania')
('0', '0-5 Years', 'Black or African American alone', '< 30 Days', 'Pennsylvania')
('0', '0-5 Years', 'Black or African American alone', '30 to < 90 Days', 'Pennsylvania')
('0', '0-5 Years', 'Black or African American alone', '90 Days to < 6 Months', 'Pennsylvania')
('0', '0-5 Years', 'Black or African American alone', '6 Months to < 1 Year', 'Pennsylvania')
('1', '0-5 Years', 'Black or African American alone', '1 Year to < 2 Years', 'Pennsylvania')
('1', '0-5 Years', 'Black or African American alone', '2 Years to < 3 Years', 'Pennsylvania')
('0', '0-5 Years', 'Black or African American alone', '3 Years to < 5 Years', 'Pennsylvania')
('6', '0-5 Years', 'Hispanic or Latino', 'All Time', 'Pennsylvania')
('0', '0-5 Years', 'Hispanic or Latino', '< 30 Days', 'Pennsylvania')
('1', '0-5 Years', 'Hispanic or Latino', '30 to < 90 Days', 'Pennsylvania')
('0', '0-5 Years', 'Hispanic or Latino', '90 Days to < 6 Months', 'Pennsylvania')
('4', '0-5 Years', 'Hispanic or Latino', '6 Months to < 1 Year', 'Pennsylvania')
('0', '0-5 Years', 'Hispanic or Latino', '1 Year to < 2 Years', 'Pennsylvania')
('1', '0-5 Years', 'Hispanic or Latino', '2 Years to < 3 Years', 'Pennsylvania')
('0', '0-5 Years', 'Hispanic or Latino', '3 Years to < 5 Years', 'Pennsylvania')
('0', '0-5 Years', 'Hispanic or Latino', '5 or More Years', 'Pennsylvania')
('1', '0-5 Years', 'Asian alone', 'All Time', 'Pennsylvania')
('0', '0-5 Years', 'Asian alone', '< 30 Days', 'Pennsylvania')
('1', '0-5 Years', 'Asian alone', '30 to < 90 Days', 'Pennsylvania')
('0', '0-5 Years', 'Asian alone', '90 Days to < 6 Months', 'Pennsylvania')
('0', '0-5 Years', 'Asian alone', '6 Months to < 1 Year', 'Pennsylvania')
('0', '0-5 Years', 'Asian alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '0-5 Years', 'Asian alone', '2 Years to < 3 Years', 'Pennsylvania')
('0', '0-5 Years', 'Asian alone', '3 Years to < 5 Years', 'Pennsylvania')
('0', '0-5 Years', 'American Indian and Alaska Native alone', 'All Time', 'Pennsylvania')
('0', '0-5 Years', 'American Indian and Alaska Native alone', '< 30 Days', 'Pennsylvania')
('0', '0-5 Years', 'American Indian and Alaska Native alone', '30 to < 90 Days', 'Pennsylvania')
('0', '0-5 Years', 'American Indian and Alaska Native alone', '90 Days to < 6 Months', 'Pennsylvania')
('0', '0-5 Years', 'American Indian and Alaska Native alone', '6 Months to < 1 Year', 'Pennsylvania')
('0', '0-5 Years', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '0-5 Years', 'Native Hawaiian and Other Pacific Islander alone', 'All Time', 'Pennsylvania')
('0', '0-5 Years', 'Native Hawaiian and Other Pacific Islander alone', '6 Months to < 1 Year', 'Pennsylvania')
('0', '0-5 Years', 'Native Hawaiian and Other Pacific Islander alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '0-5 Years', 'Population of two or more races:', 'All Time', 'Pennsylvania')
('0', '0-5 Years', 'Population of two or more races:', '< 30 Days', 'Pennsylvania')
('0', '0-5 Years', 'Population of two or more races:', '30 to < 90 Days', 'Pennsylvania')
('0', '0-5 Years', 'Population of two or more races:', '90 Days to < 6 Months', 'Pennsylvania')
('0', '0-5 Years', 'Population of two or more races:', '6 Months to < 1 Year', 'Pennsylvania')
('0', '0-5 Years', 'Population of two or more races:', '1 Year to < 2 Years', 'Pennsylvania')
('0', '0-5 Years', 'Population of two or more races:', '2 Years to < 3 Years', 'Pennsylvania')
('13', '6-10 Years', 'White alone', 'All Time', 'Pennsylvania')
('0', '6-10 Years', 'White alone', '< 30 Days', 'Pennsylvania')
('0', '6-10 Years', 'White alone', '30 to < 90 Days', 'Pennsylvania')
('2', '6-10 Years', 'White alone', '90 Days to < 6 Months', 'Pennsylvania')
('2', '6-10 Years', 'White alone', '6 Months to < 1 Year', 'Pennsylvania')
('1', '6-10 Years', 'White alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '6-10 Years', 'White alone', '2 Years to < 3 Years', 'Pennsylvania')
('3', '6-10 Years', 'White alone', '3 Years to < 5 Years', 'Pennsylvania')
('5', '6-10 Years', 'White alone', '5 or More Years', 'Pennsylvania')
('8', '6-10 Years', 'Black or African American alone', 'All Time', 'Pennsylvania')
('0', '6-10 Years', 'Black or African American alone', '< 30 Days', 'Pennsylvania')
('0', '6-10 Years', 'Black or African American alone', '30 to < 90 Days', 'Pennsylvania')
('1', '6-10 Years', 'Black or African American alone', '90 Days to < 6 Months', 'Pennsylvania')
('1', '6-10 Years', 'Black or African American alone', '6 Months to < 1 Year', 'Pennsylvania')
('1', '6-10 Years', 'Black or African American alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '6-10 Years', 'Black or African American alone', '2 Years to < 3 Years', 'Pennsylvania')
('0', '6-10 Years', 'Black or African American alone', '3 Years to < 5 Years', 'Pennsylvania')
('5', '6-10 Years', 'Black or African American alone', '5 or More Years', 'Pennsylvania')
('4', '6-10 Years', 'Hispanic or Latino', 'All Time', 'Pennsylvania')
('1', '6-10 Years', 'Hispanic or Latino', '< 30 Days', 'Pennsylvania')
('0', '6-10 Years', 'Hispanic or Latino', '30 to < 90 Days', 'Pennsylvania')
('0', '6-10 Years', 'Hispanic or Latino', '90 Days to < 6 Months', 'Pennsylvania')
('0', '6-10 Years', 'Hispanic or Latino', '6 Months to < 1 Year', 'Pennsylvania')
('0', '6-10 Years', 'Hispanic or Latino', '1 Year to < 2 Years', 'Pennsylvania')
('0', '6-10 Years', 'Hispanic or Latino', '2 Years to < 3 Years', 'Pennsylvania')
('0', '6-10 Years', 'Hispanic or Latino', '3 Years to < 5 Years', 'Pennsylvania')
('3', '6-10 Years', 'Hispanic or Latino', '5 or More Years', 'Pennsylvania')
('2', '6-10 Years', 'Asian alone', 'All Time', 'Pennsylvania')
('0', '6-10 Years', 'Asian alone', '< 30 Days', 'Pennsylvania')
('0', '6-10 Years', 'Asian alone', '30 to < 90 Days', 'Pennsylvania')
('1', '6-10 Years', 'Asian alone', '6 Months to < 1 Year', 'Pennsylvania')
('0', '6-10 Years', 'Asian alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '6-10 Years', 'Asian alone', '2 Years to < 3 Years', 'Pennsylvania')
('0', '6-10 Years', 'Asian alone', '3 Years to < 5 Years', 'Pennsylvania')
('1', '6-10 Years', 'Asian alone', '5 or More Years', 'Pennsylvania')
('0', '6-10 Years', 'American Indian and Alaska Native alone', 'All Time', 'Pennsylvania')
('0', '6-10 Years', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '6-10 Years', 'American Indian and Alaska Native alone', '3 Years to < 5 Years', 'Pennsylvania')
('0', '6-10 Years', 'Native Hawaiian and Other Pacific Islander alone', 'All Time', 'Pennsylvania')
('0', '6-10 Years', 'Native Hawaiian and Other Pacific Islander alone', '6 Months to < 1 Year', 'Pennsylvania')
('0', '6-10 Years', 'Native Hawaiian and Other Pacific Islander alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '6-10 Years', 'Native Hawaiian and Other Pacific Islander alone', '3 Years to < 5 Years', 'Pennsylvania')
('0', '6-10 Years', 'Population of two or more races:', 'All Time', 'Pennsylvania')
('0', '6-10 Years', 'Population of two or more races:', '< 30 Days', 'Pennsylvania')
('0', '6-10 Years', 'Population of two or more races:', '90 Days to < 6 Months', 'Pennsylvania')
('0', '6-10 Years', 'Population of two or more races:', '6 Months to < 1 Year', 'Pennsylvania')
('0', '6-10 Years', 'Population of two or more races:', '1 Year to < 2 Years', 'Pennsylvania')
('0', '6-10 Years', 'Population of two or more races:', '2 Years to < 3 Years', 'Pennsylvania')
('0', '6-10 Years', 'Population of two or more races:', '3 Years to < 5 Years', 'Pennsylvania')
('0', '6-10 Years', 'Population of two or more races:', '5 or More Years', 'Pennsylvania')
('19', '11-17 Years', 'White alone', 'All Time', 'Pennsylvania')
('1', '11-17 Years', 'White alone', '< 30 Days', 'Pennsylvania')
('5', '11-17 Years', 'White alone', '30 to < 90 Days', 'Pennsylvania')
('1', '11-17 Years', 'White alone', '90 Days to < 6 Months', 'Pennsylvania')
('5', '11-17 Years', 'White alone', '6 Months to < 1 Year', 'Pennsylvania')
('3', '11-17 Years', 'White alone', '1 Year to < 2 Years', 'Pennsylvania')
('1', '11-17 Years', 'White alone', '2 Years to < 3 Years', 'Pennsylvania')
('1', '11-17 Years', 'White alone', '3 Years to < 5 Years', 'Pennsylvania')
('2', '11-17 Years', 'White alone', '5 or More Years', 'Pennsylvania')
('4', '11-17 Years', 'Black or African American alone', 'All Time', 'Pennsylvania')
('0', '11-17 Years', 'Black or African American alone', '< 30 Days', 'Pennsylvania')
('0', '11-17 Years', 'Black or African American alone', '30 to < 90 Days', 'Pennsylvania')
('1', '11-17 Years', 'Black or African American alone', '90 Days to < 6 Months', 'Pennsylvania')
('0', '11-17 Years', 'Black or African American alone', '6 Months to < 1 Year', 'Pennsylvania')
('1', '11-17 Years', 'Black or African American alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '11-17 Years', 'Black or African American alone', '2 Years to < 3 Years', 'Pennsylvania')
('2', '11-17 Years', 'Black or African American alone', '3 Years to < 5 Years', 'Pennsylvania')
('0', '11-17 Years', 'Black or African American alone', '5 or More Years', 'Pennsylvania')
('7', '11-17 Years', 'Hispanic or Latino', 'All Time', 'Pennsylvania')
('0', '11-17 Years', 'Hispanic or Latino', '< 30 Days', 'Pennsylvania')
('1', '11-17 Years', 'Hispanic or Latino', '30 to < 90 Days', 'Pennsylvania')
('0', '11-17 Years', 'Hispanic or Latino', '90 Days to < 6 Months', 'Pennsylvania')
('4', '11-17 Years', 'Hispanic or Latino', '6 Months to < 1 Year', 'Pennsylvania')
('1', '11-17 Years', 'Hispanic or Latino', '1 Year to < 2 Years', 'Pennsylvania')
('1', '11-17 Years', 'Hispanic or Latino', '2 Years to < 3 Years', 'Pennsylvania')
('0', '11-17 Years', 'Hispanic or Latino', '3 Years to < 5 Years', 'Pennsylvania')
('0', '11-17 Years', 'Hispanic or Latino', '5 or More Years', 'Pennsylvania')
('2', '11-17 Years', 'Asian alone', 'All Time', 'Pennsylvania')
('0', '11-17 Years', 'Asian alone', '< 30 Days', 'Pennsylvania')
('1', '11-17 Years', 'Asian alone', '30 to < 90 Days', 'Pennsylvania')
('1', '11-17 Years', 'Asian alone', '90 Days to < 6 Months', 'Pennsylvania')
('0', '11-17 Years', 'Asian alone', '6 Months to < 1 Year', 'Pennsylvania')
('0', '11-17 Years', 'Asian alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '11-17 Years', 'Asian alone', '2 Years to < 3 Years', 'Pennsylvania')
('0', '11-17 Years', 'Asian alone', '3 Years to < 5 Years', 'Pennsylvania')
('0', '11-17 Years', 'Asian alone', '5 or More Years', 'Pennsylvania')
('0', '11-17 Years', 'American Indian and Alaska Native alone', 'All Time', 'Pennsylvania')
('0', '11-17 Years', 'American Indian and Alaska Native alone', '90 Days to < 6 Months', 'Pennsylvania')
('0', '11-17 Years', 'American Indian and Alaska Native alone', '6 Months to < 1 Year', 'Pennsylvania')
('0', '11-17 Years', 'American Indian and Alaska Native alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '11-17 Years', 'American Indian and Alaska Native alone', '2 Years to < 3 Years', 'Pennsylvania')
('0', '11-17 Years', 'American Indian and Alaska Native alone', '3 Years to < 5 Years', 'Pennsylvania')
('0', '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', 'All Time', 'Pennsylvania')
('0', '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', '30 to < 90 Days', 'Pennsylvania')
('0', '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', '90 Days to < 6 Months', 'Pennsylvania')
('0', '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', '1 Year to < 2 Years', 'Pennsylvania')
('0', '11-17 Years', 'Native Hawaiian and Other Pacific Islander alone', '5 or More Years', 'Pennsylvania')
('1', '11-17 Years', 'Population of two or more races:', 'All Time', 'Pennsylvania')
('0', '11-17 Years', 'Population of two or more races:', '< 30 Days', 'Pennsylvania')
('1', '11-17 Years', 'Population of two or more races:', '30 to < 90 Days', 'Pennsylvania')
('0', '11-17 Years', 'Population of two or more races:', '90 Days to < 6 Months', 'Pennsylvania')
('0', '11-17 Years', 'Population of two or more races:', '6 Months to < 1 Year', 'Pennsylvania')
('0', '11-17 Years', 'Population of two or more races:', '1 Year to < 2 Years', 'Pennsylvania')
('0', '11-17 Years', 'Population of two or more races:', '2 Years to < 3 Years', 'Pennsylvania')
('0', '11-17 Years', 'Population of two or more races:', '3 Years to < 5 Years', 'Pennsylvania')
('0', '11-17 Years', 'Population of two or more races:', '5 or More Years', 'Pennsylvania')
('165', '18-34 Years', 'White alone', 'All Time', 'Pennsylvania')
('5', '18-34 Years', 'White alone', '< 30 Days', 'Pennsylvania')
('25', '18-34 Years', 'White alone', '30 to < 90 Days', 'Pennsylvania')
('21', '18-34 Years', 'White alone', '90 Days to < 6 Months', 'Pennsylvania')
('34', '18-34 Years', 'White alone', '6 Months to < 1 Year', 'Pennsylvania')
('34', '18-34 Years', 'White alone', '1 Year to < 2 Years', 'Pennsylvania')
('20', '18-34 Years', 'White alone', '2 Years to < 3 Years', 'Pennsylvania')
('20', '18-34 Years', 'White alone', '3 Years to < 5 Years', 'Pennsylvania')
('6', '18-34 Years', 'White alone', '5 or More Years', 'Pennsylvania')
('134', '18-34 Years', 'Black or African American alone', 'All Time', 'Pennsylvania')
('3', '18-34 Years', 'Black or African American alone', '< 30 Days', 'Pennsylvania')
('12', '18-34 Years', 'Black or African American alone', '30 to < 90 Days', 'Pennsylvania')
('8', '18-34 Years', 'Black or African American alone', '90 Days to < 6 Months', 'Pennsylvania')
('21', '18-34 Years', 'Black or African American alone', '6 Months to < 1 Year', 'Pennsylvania')
('36', '18-34 Years', 'Black or African American alone', '1 Year to < 2 Years', 'Pennsylvania')
('18', '18-34 Years', 'Black or African American alone', '2 Years to < 3 Years', 'Pennsylvania')

In [324]:
census_age = pd.read_csv('output/census_age_final.csv')
census_ethn = pd.read_csv('output/census_eth_df_drop.csv')
age_ethnicity_state = pd.read_csv('output/all_waittimes.csv')
age_waittime_state = pd.read_csv('output/all_ethnicities.csv')

In [329]:
age_waittime_state

,Index,Age,Ethnicities,Wait Time,All Patient States,Alabama,Alaska,Arizona,Arkansas,California,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,0,All Ages,All Ethnicities,All Time,"114,059","1,638",142,"1,156",485,"21,066",...,323,"2,149","11,181",613,159,"3,339","1,479",407,"1,506",97
1,1,All Ages,All Ethnicities,< 30 Days,"5,234",39,4,81,32,671,...,17,110,490,44,5,153,72,31,77,5
2,2,All Ages,All Ethnicities,30 to < 90 Days,"9,368",92,10,116,59,"1,202",...,20,176,"1,015",80,7,319,109,47,146,15
3,3,All Ages,All Ethnicities,90 Days to < 6 Months,"10,151",167,12,155,68,"1,311",...,24,208,993,74,20,336,139,59,141,12
4,4,All Ages,All Ethnicities,6 Months to < 1 Year,"17,886",337,13,206,93,"2,544",...,48,415,"1,898",116,25,582,264,82,253,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,475,65 and Older,All Ethnicities,6 Months to < 1 Year,"4,174",72,3,36,18,517,...,9,118,319,28,7,136,67,13,68,4
68,476,65 and Older,All Ethnicities,1 Year to < 2 Years,"6,005",94,9,46,24,828,...,20,95,482,33,18,195,83,18,98,5
69,477,65 and Older,All Ethnicities,2 Years to < 3 Years,"3,821",63,5,32,11,684,...,5,81,301,18,9,114,73,6,54,2
70,478,65 and Older,All Ethnicities,3 Years to < 5 Years,"5,025",55,12,31,11,"1,096",...,14,90,385,16,7,128,83,10,54,4
71,479,65 and Older,All Ethnicities,5 or More Years,"3,865",27,6,40,3,"1,263",...,20,36,255,4,1,78,33,8,29,2

In [299]:
#census_age = census_age.drop('Unnamed: 0', axis=1)
#census_ethn = census_ethn.drop('Unnamed: 0', axis=1)

In [336]:
census_ethn.to_sql('census_ethnicities', conn, if_exists='append', index = True)
census_age.to_sql('census_ages', conn, if_exists='append', index = False)
age_ethnicity_state.to_sql('age_thnicity_state', conn, if_exists='append', index = False)
age_waittime_state.to_sql('age_waittime_state', conn, if_exists='append', index = False)

In [352]:
data = c.execute("SELECT * FROM census_ethnicities")
#SELECT rowid, * FROM tbl1 WHERE letter = 'B'
for record in data:
    print(record)

(0, 'Total:', '331,449,281', '5,024,279', '733,391', '7,151,502', '3,011,524', '39,538,223', '5,773,714', '3,605,944', '989,948', '689,545', '21,538,187', '10,711,908', '1,455,271', '1,839,106', '12,812,508', '6,785,528', '3,190,369', '2,937,880', '4,505,836', '4,657,757', '1,362,359', '6,177,224', '7,029,917', '10,077,331', '5,706,494', '2,961,279', '6,154,913', '1,084,225', '1,961,504', '3,104,614', '1,377,529', '9,288,994', '2,117,522', '20,201,249', '10,439,388', '779,094', '11,799,448', '3,959,353', '4,237,256', '13,002,700', '1,097,379', '5,118,425', '886,667', '6,910,840', '29,145,505', '3,271,616', '643,077', '8,631,393', '7,705,281', '1,793,716', '5,893,718', '3,285,874')
(1, 'Hispanic or Latino', '62,080,044', '264,047', '49,824', '2,192,253', '256,847', '15,579,652', '1,263,390', '623,293', '104,290', '77,652', '5,697,240', '1,123,457', '138,923', '239,407', '2,337,410', '554,191', '215,986', '382,603', '207,854', '322,549', '26,609', '729,745', '887,685', '564,422', '345,640', '105,220', '303,068', '45,199', '234,715', '890,257', '59,454', '2,002,575', '1,010,811', '3,948,032', '1,118,596', '33,412', '521,308', '471,931', '588,757', '1,049,615', '182,101', '352,838', '38,741', '479,187', '11,441,717', '492,912', '15,504', '908,749', '1,059,213', '34,827', '447,290', '3,249,043')
(4, 'White alone', '191,697,647', '3,171,351', '421,758', '3,816,547', '2,063,550', '13,714,587', '3,760,663', '2,279,232', '579,851', '261,771', '11,100,503', '5,362,156', '314,365', '1,450,523', '7,472,751', '5,121,004', '2,638,201', '2,122,575', '3,664,764', '2,596,702', '1,228,264', '2,913,782', '4,748,897', '7,295,651', '4,353,880', '1,639,077', '4,663,907', '901,318', '1,484,687', '1,425,952', '1,200,649', '4,816,381', '772,952', '10,598,907', '6,312,148', '636,160', '8,954,135', '2,407,188', '3,036,158', '9,553,417', '754,050', '3,178,552', '705,583', '4,900,246', '11,584,597', '2,465,355', '573,201', '5,058,363', '4,918,820', '1,598,834', '4,634,018', '24,548')
(5, 'Black or African American alone', '39,940,338', '1,288,159', '20,731', '317,161', '449,884', '2,119,286', '221,310', '360,937', '212,960', '282,066', '3,127,052', '3,278,119', '21,877', '14,785', '1,775,612', '637,500', '129,321', '163,352', '357,764', '1,452,420', '25,115', '1,795,027', '457,055', '1,358,458', '392,850', '1,079,001', '692,774', '5,077', '94,405', '291,960', '18,655', '1,154,142', '38,330', '2,759,022', '2,107,526', '26,152', '1,457,180', '283,242', '78,658', '1,368,978', '55,386', '1,269,031', '17,441', '1,083,772', '3,444,712', '37,192', '8,649', '1,578,090', '296,170', '64,749', '366,508', '4,286')
(6, 'American Indian and Alaska Native alone', '2,251,699', '23,119', '108,838', '263,930', '20,549', '156,085', '33,768', '6,404', '2,521', '1,277', '42,169', '20,375', '2,321', '18,903', '16,561', '12,938', '9,079', '21,921', '8,080', '25,994', '7,293', '12,055', '9,387', '47,406', '57,046', '14,019', '23,496', '64,592', '15,051', '23,392', '2,299', '11,206', '188,610', '54,908', '100,886', '37,350', '18,949', '311,890', '42,042', '15,028', '3,513', '16,591', '74,595', '15,539', '85,425', '28,690', '1,986', '19,080', '91,191', '3,187', '48,384', '312')
(7, 'Asian alone', '19,618,719', '75,918', '43,449', '248,837', '51,210', '5,978,795', '195,220', '170,459', '42,398', '33,192', '629,626', '475,680', '531,558', '26,036', '747,280', '166,651', '75,017', '85,225', '73,843', '85,336', '16,668', '417,962', '504,900', '332,288', '297,460', '32,305', '132,158', '8,077', '52,359', '265,991', '35,604', '942,921', '35,261', '1,916,329', '340,059', '13,050', '296,604', '89,653', '191,797', '506,674', '38,367', '89,394', '13,332', '134,302', '1,561,518', '78,618', '11,457', '610,612', '723,062', '14,903', '174,267', '2,746')
(8, 'Native Hawaiian and Other Pacific Islander alone', '622,018', '2,612', '12,455', '14,323', '14,280', '138,167', '9,005', '974', '304', '349', '11,521', '6,101', '149,054', '3,401', '2,959', '2,761', '5,605', '3,115', '3,462', '1,706', '407', '2,575', '1,607', '2,603', '2,621', '1,037', '9,293', '839', '1,318', '22,970', '388', '1,944', '1,451', '6,097', '6,980', '869', '4,493', '8,168', '18,197', '3,162', '320', '3,085', '493', '3,594', '27,857', '35,831', '170', '6,195', '62,490', '429', '1,892', '91')
(9, 'Some Other Race alone', '1,689,833', '14,455', '4,575', '31,611', '8,047', '223,929', '29,560', '27,076', '4,601', '3,753', '137,933', '55,887', '5,283', '8,243', '45,080', '25,139', '8,487', '10,064', '14,706', '16,954', '4,430', '35,314', '92,108', '37,183', '20,963', '7,174', '22,377', '4,374', '6,335', '17,171', '5,916', '70,354', '10,340', '197,107', '46,340', '1,853', '45,217', '13,602', '22,962', '54,541', '11,392', '19,354', '2,050', '23,977', '113,584', '12,566', '2,561', '45,394', '43,221', '4,652', '17,613', '2,508')
(10, 'Population of two or more races:', '13,548,983', '184,618', '71,761', '266,840', '147,157', '1,627,722', '260,798', '137,569', '43,023', '29,485', '792,143', '390,133', '291,890', '77,808', '414,855', '265,344', '108,673', '149,025', '175,363', '156,096', '53,573', '270,764', '328,278', '439,320', '236,034', '83,446', '307,840', '54,749', '72,634', '166,921', '54,564', '289,471', '59,767', '720,847', '406,853', '30,248', '501,562', '373,679', '258,685', '451,285', '52,250', '189,580', '34,432', '270,223', '886,095', '120,452', '29,549', '404,910', '511,114', '72,135', '203,746', '2,340')
(0, 'Total:', '331,449,281', '5,024,279', '733,391', '7,151,502', '3,011,524', '39,538,223', '5,773,714', '3,605,944', '989,948', '689,545', '21,538,187', '10,711,908', '1,455,271', '1,839,106', '12,812,508', '6,785,528', '3,190,369', '2,937,880', '4,505,836', '4,657,757', '1,362,359', '6,177,224', '7,029,917', '10,077,331', '5,706,494', '2,961,279', '6,154,913', '1,084,225', '1,961,504', '3,104,614', '1,377,529', '9,288,994', '2,117,522', '20,201,249', '10,439,388', '779,094', '11,799,448', '3,959,353', '4,237,256', '13,002,700', '1,097,379', '5,118,425', '886,667', '6,910,840', '29,145,505', '3,271,616', '643,077', '8,631,393', '7,705,281', '1,793,716', '5,893,718', '3,285,874')
(1, 'Hispanic or Latino', '62,080,044', '264,047', '49,824', '2,192,253', '256,847', '15,579,652', '1,263,390', '623,293', '104,290', '77,652', '5,697,240', '1,123,457', '138,923', '239,407', '2,337,410', '554,191', '215,986', '382,603', '207,854', '322,549', '26,609', '729,745', '887,685', '564,422', '345,640', '105,220', '303,068', '45,199', '234,715', '890,257', '59,454', '2,002,575', '1,010,811', '3,948,032', '1,118,596', '33,412', '521,308', '471,931', '588,757', '1,049,615', '182,101', '352,838', '38,741', '479,187', '11,441,717', '492,912', '15,504', '908,749', '1,059,213', '34,827', '447,290', '3,249,043')
(4, 'White alone', '191,697,647', '3,171,351', '421,758', '3,816,547', '2,063,550', '13,714,587', '3,760,663', '2,279,232', '579,851', '261,771', '11,100,503', '5,362,156', '314,365', '1,450,523', '7,472,751', '5,121,004', '2,638,201', '2,122,575', '3,664,764', '2,596,702', '1,228,264', '2,913,782', '4,748,897', '7,295,651', '4,353,880', '1,639,077', '4,663,907', '901,318', '1,484,687', '1,425,952', '1,200,649', '4,816,381', '772,952', '10,598,907', '6,312,148', '636,160', '8,954,135', '2,407,188', '3,036,158', '9,553,417', '754,050', '3,178,552', '705,583', '4,900,246', '11,584,597', '2,465,355', '573,201', '5,058,363', '4,918,820', '1,598,834', '4,634,018', '24,548')
(5, 'Black or African American alone', '39,940,338', '1,288,159', '20,731', '317,161', '449,884', '2,119,286', '221,310', '360,937', '212,960', '282,066', '3,127,052', '3,278,119', '21,877', '14,785', '1,775,612', '637,500', '129,321', '163,352', '357,764', '1,452,420', '25,115', '1,795,027', '457,055', '1,358,458', '392,850', '1,079,001', '692,774', '5,077', '94,405', '291,960', '18,655', '1,154,142', '38,330', '2,759,022', '2,107,526', '26,152', '1,457,180', '283,242', '78,658', '1,368,978', '55,386', '1,269,031', '17,441', '1,083,772', '3,444,712', '37,192', '8,649', '1,578,090', '296,170', '64,749', '366,508', '4,286')
(6, 'American Indian and Alaska Native alone', '2,251,699', '23,119', '108,838', '263,930', '20,549', '156,085', '33,768', '6,404', '2,521', '1,277', '42,169', '20,375', '2,321', '18,903', '16,561', '12,938', '9,079', '21,921', '8,080', '25,994', '7,293', '12,055', '9,387', '47,406', '57,046', '14,019', '23,496', '64,592', '15,051', '23,392', '2,299', '11,206', '188,610', '54,908', '100,886', '37,350', '18,949', '311,890', '42,042', '15,028', '3,513', '16,591', '74,595', '15,539', '85,425', '28,690', '1,986', '19,080', '91,191', '3,187', '48,384', '312')
(7, 'Asian alone', '19,618,719', '75,918', '43,449', '248,837', '51,210', '5,978,795', '195,220', '170,459', '42,398', '33,192', '629,626', '475,680', '531,558', '26,036', '747,280', '166,651', '75,017', '85,225', '73,843', '85,336', '16,668', '417,962', '504,900', '332,288', '297,460', '32,305', '132,158', '8,077', '52,359', '265,991', '35,604', '942,921', '35,261', '1,916,329', '340,059', '13,050', '296,604', '89,653', '191,797', '506,674', '38,367', '89,394', '13,332', '134,302', '1,561,518', '78,618', '11,457', '610,612', '723,062', '14,903', '174,267', '2,746')
(8, 'Native Hawaiian and Other Pacific Islander alone', '622,018', '2,612', '12,455', '14,323', '14,280', '138,167', '9,005', '974', '304', '349', '11,521', '6,101', '149,054', '3,401', '2,959', '2,761', '5,605', '3,115', '3,462', '1,706', '407', '2,575', '1,607', '2,603', '2,621', '1,037', '9,293', '839', '1,318', '22,970', '388', '1,944', '1,451', '6,097', '6,980', '869', '4,493', '8,168', '18,197', '3,162', '320', '3,085', '493', '3,594', '27,857', '35,831', '170', '6,195', '62,490', '429', '1,892', '91')
(9, 'Some Other Race alone', '1,689,833', '14,455', '4,575', '31,611', '8,047', '223,929', '29,560', '27,076', '4,601', '3,753', '137,933', '55,887', '5,283', '8,243', '45,080', '25,139', '8,487', '10,064', '14,706', '16,954', '4,430', '35,314', '92,108', '37,183', '20,963', '7,174', '22,377', '4,374', '6,335', '17,171', '5,916', '70,354', '10,340', '197,107', '46,340', '1,853', '45,217', '13,602', '22,962', '54,541', '11,392', '19,354', '2,050', '23,977', '113,584', '12,566', '2,561', '45,394', '43,221', '4,652', '17,613', '2,508')
(10, 'Population of two or more races:', '13,548,983', '184,618', '71,761', '266,840', '147,157', '1,627,722', '260,798', '137,569', '43,023', '29,485', '792,143', '390,133', '291,890', '77,808', '414,855', '265,344', '108,673', '149,025', '175,363', '156,096', '53,573', '270,764', '328,278', '439,320', '236,034', '83,446', '307,840', '54,749', '72,634', '166,921', '54,564', '289,471', '59,767', '720,847', '406,853', '30,248', '501,562', '373,679', '258,685', '451,285', '52,250', '189,580', '34,432', '270,223', '886,095', '120,452', '29,549', '404,910', '511,114', '72,135', '203,746', '2,340')
(0, 'Total:', '331,449,281', '5,024,279', '733,391', '7,151,502', '3,011,524', '39,538,223', '5,773,714', '3,605,944', '989,948', '689,545', '21,538,187', '10,711,908', '1,455,271', '1,839,106', '12,812,508', '6,785,528', '3,190,369', '2,937,880', '4,505,836', '4,657,757', '1,362,359', '6,177,224', '7,029,917', '10,077,331', '5,706,494', '2,961,279', '6,154,913', '1,084,225', '1,961,504', '3,104,614', '1,377,529', '9,288,994', '2,117,522', '20,201,249', '10,439,388', '779,094', '11,799,448', '3,959,353', '4,237,256', '13,002,700', '1,097,379', '5,118,425', '886,667', '6,910,840', '29,145,505', '3,271,616', '643,077', '8,631,393', '7,705,281', '1,793,716', '5,893,718', '3,285,874')
(1, 'Hispanic or Latino', '62,080,044', '264,047', '49,824', '2,192,253', '256,847', '15,579,652', '1,263,390', '623,293', '104,290', '77,652', '5,697,240', '1,123,457', '138,923', '239,407', '2,337,410', '554,191', '215,986', '382,603', '207,854', '322,549', '26,609', '729,745', '887,685', '564,422', '345,640', '105,220', '303,068', '45,199', '234,715', '890,257', '59,454', '2,002,575', '1,010,811', '3,948,032', '1,118,596', '33,412', '521,308', '471,931', '588,757', '1,049,615', '182,101', '352,838', '38,741', '479,187', '11,441,717', '492,912', '15,504', '908,749', '1,059,213', '34,827', '447,290', '3,249,043')
(2, 'White alone', '191,697,647', '3,171,351', '421,758', '3,816,547', '2,063,550', '13,714,587', '3,760,663', '2,279,232', '579,851', '261,771', '11,100,503', '5,362,156', '314,365', '1,450,523', '7,472,751', '5,121,004', '2,638,201', '2,122,575', '3,664,764', '2,596,702', '1,228,264', '2,913,782', '4,748,897', '7,295,651', '4,353,880', '1,639,077', '4,663,907', '901,318', '1,484,687', '1,425,952', '1,200,649', '4,816,381', '772,952', '10,598,907', '6,312,148', '636,160', '8,954,135', '2,407,188', '3,036,158', '9,553,417', '754,050', '3,178,552', '705,583', '4,900,246', '11,584,597', '2,465,355', '573,201', '5,058,363', '4,918,820', '1,598,834', '4,634,018', '24,548')
(3, 'Black or African American alone', '39,940,338', '1,288,159', '20,731', '317,161', '449,884', '2,119,286', '221,310', '360,937', '212,960', '282,066', '3,127,052', '3,278,119', '21,877', '14,785', '1,775,612', '637,500', '129,321', '163,352', '357,764', '1,452,420', '25,115', '1,795,027', '457,055', '1,358,458', '392,850', '1,079,001', '692,774', '5,077', '94,405', '291,960', '18,655', '1,154,142', '38,330', '2,759,022', '2,107,526', '26,152', '1,457,180', '283,242', '78,658', '1,368,978', '55,386', '1,269,031', '17,441', '1,083,772', '3,444,712', '37,192', '8,649', '1,578,090', '296,170', '64,749', '366,508', '4,286')
(4, 'American Indian and Alaska Native alone', '2,251,699', '23,119', '108,838', '263,930', '20,549', '156,085', '33,768', '6,404', '2,521', '1,277', '42,169', '20,375', '2,321', '18,903', '16,561', '12,938', '9,079', '21,921', '8,080', '25,994', '7,293', '12,055', '9,387', '47,406', '57,046', '14,019', '23,496', '64,592', '15,051', '23,392', '2,299', '11,206', '188,610', '54,908', '100,886', '37,350', '18,949', '311,890', '42,042', '15,028', '3,513', '16,591', '74,595', '15,539', '85,425', '28,690', '1,986', '19,080', '91,191', '3,187', '48,384', '312')
(5, 'Asian alone', '19,618,719', '75,918', '43,449', '248,837', '51,210', '5,978,795', '195,220', '170,459', '42,398', '33,192', '629,626', '475,680', '531,558', '26,036', '747,280', '166,651', '75,017', '85,225', '73,843', '85,336', '16,668', '417,962', '504,900', '332,288', '297,460', '32,305', '132,158', '8,077', '52,359', '265,991', '35,604', '942,921', '35,261', '1,916,329', '340,059', '13,050', '296,604', '89,653', '191,797', '506,674', '38,367', '89,394', '13,332', '134,302', '1,561,518', '78,618', '11,457', '610,612', '723,062', '14,903', '174,267', '2,746')
(6, 'Native Hawaiian and Other Pacific Islander alone', '622,018', '2,612', '12,455', '14,323', '14,280', '138,167', '9,005', '974', '304', '349', '11,521', '6,101', '149,054', '3,401', '2,959', '2,761', '5,605', '3,115', '3,462', '1,706', '407', '2,575', '1,607', '2,603', '2,621', '1,037', '9,293', '839', '1,318', '22,970', '388', '1,944', '1,451', '6,097', '6,980', '869', '4,493', '8,168', '18,197', '3,162', '320', '3,085', '493', '3,594', '27,857', '35,831', '170', '6,195', '62,490', '429', '1,892', '91')
(7, 'Some Other Race alone', '1,689,833', '14,455', '4,575', '31,611', '8,047', '223,929', '29,560', '27,076', '4,601', '3,753', '137,933', '55,887', '5,283', '8,243', '45,080', '25,139', '8,487', '10,064', '14,706', '16,954', '4,430', '35,314', '92,108', '37,183', '20,963', '7,174', '22,377', '4,374', '6,335', '17,171', '5,916', '70,354', '10,340', '197,107', '46,340', '1,853', '45,217', '13,602', '22,962', '54,541', '11,392', '19,354', '2,050', '23,977', '113,584', '12,566', '2,561', '45,394', '43,221', '4,652', '17,613', '2,508')
(8, 'Population of two or more races:', '13,548,983', '184,618', '71,761', '266,840', '147,157', '1,627,722', '260,798', '137,569', '43,023', '29,485', '792,143', '390,133', '291,890', '77,808', '414,855', '265,344', '108,673', '149,025', '175,363', '156,096', '53,573', '270,764', '328,278', '439,320', '236,034', '83,446', '307,840', '54,749', '72,634', '166,921', '54,564', '289,471', '59,767', '720,847', '406,853', '30,248', '501,562', '373,679', '258,685', '451,285', '52,250', '189,580', '34,432', '270,223', '886,095', '120,452', '29,549', '404,910', '511,114', '72,135', '203,746', '2,340')

In [353]:
census_eth_df_percent = pd.read_csv('output/census_eth_df_percent.csv')
census_age_percent = pd.read_csv('output/census_age_percent.csv')

In [354]:
census_eth_df_percent.to_sql('census_eth_df_percent', conn, if_exists='append', index = False)
census_age_percent.to_sql('census_age_percent', conn, if_exists='append', index = False)

In [355]:
data_census = c.execute("SELECT * FROM census_age_percent")

for record in data_census:
    print(record)

(1, '0-5 years', 5.8, 6.03, 6.22, 5.4, 6.18, 5.39, 5.61, 4.74, 5.07, 5.54, 4.95, 5.83, 4.42, 6.93, 5.83, 6.48, 6.48, 6.52, 6.44, 6.23, 5.18, 5.52, 4.89, 5.79, 6.1, 6.17, 6.25, 5.85, 6.72, 5.0, 4.98, 5.58, 5.23, 5.69, 5.51, 7.02, 6.13, 6.08, 5.14, 5.45, 4.61, 5.58, 6.75, 6.06, 6.7, 8.07, 4.98, 5.81, 5.48, 5.84, 5.61, 4.31)
(2, '6-10 Years', 5.26, 5.42, 5.49, 4.86, 5.62, 4.72, 5.14, 4.54, 4.62, 3.24, 4.43, 5.42, 4.57, 6.69, 5.39, 5.74, 5.84, 5.99, 5.78, 5.64, 4.69, 5.03, 4.49, 5.25, 5.47, 5.5, 5.57, 5.7, 6.07, 4.85, 4.64, 4.99, 5.18, 4.95, 5.0, 6.06, 5.47, 5.6, 4.91, 4.93, 4.21, 5.16, 6.1, 5.43, 6.17, 7.69, 4.63, 5.28, 5.07, 5.38, 5.1, 4.7)
(3, '11-17 years', 7.95, 8.4, 8.09, 7.12, 8.72, 7.31, 7.81, 7.26, 6.8, 3.15, 6.76, 8.58, 5.03, 9.69, 7.86, 8.81, 8.68, 8.77, 8.74, 8.49, 7.32, 7.65, 7.11, 8.08, 8.22, 8.87, 8.41, 7.94, 8.99, 7.14, 7.52, 8.02, 6.82, 7.48, 7.72, 8.6, 8.25, 8.48, 7.45, 7.59, 6.52, 7.74, 8.67, 8.02, 8.92, 11.28, 7.52, 7.8, 7.44, 8.18, 8.04, 7.74)
(4, '18-34 years', 20.96, 20.44, 22.74, 20.13, 20.45, 21.09, 23.65, 19.92, 18.93, 38.84, 18.18, 21.37, 22.72, 21.07, 20.58, 21.65, 21.15, 21.55, 21.23, 20.65, 19.46, 20.36, 22.15, 20.98, 20.26, 20.22, 21.1, 21.14, 21.3, 19.26, 20.99, 19.31, 19.54, 21.33, 21.14, 23.9, 21.03, 21.14, 20.86, 20.33, 22.16, 20.34, 20.66, 21.39, 22.11, 25.11, 21.61, 21.58, 21.47, 19.72, 20.5, 21.17)
(5, '35-49 years', 18.62, 18.59, 20.43, 17.48, 18.59, 19.15, 20.43, 17.67, 16.94, 24.83, 16.74, 19.03, 19.45, 18.69, 19.06, 18.61, 18.22, 18.31, 18.95, 19.23, 18.18, 18.73, 18.05, 18.06, 19.16, 18.64, 18.77, 18.48, 18.63, 19.33, 18.06, 17.9, 17.77, 18.11, 18.76, 18.17, 18.43, 19.03, 19.89, 18.16, 17.75, 18.28, 17.84, 19.0, 19.32, 19.38, 18.0, 19.22, 19.92, 18.72, 18.51, 18.5)
(6, '50-64 years', 20.6, 20.7, 20.44, 19.95, 19.78, 20.79, 19.43, 23.15, 21.92, 12.76, 21.18, 20.65, 19.77, 18.36, 20.99, 20.08, 19.69, 19.37, 20.26, 20.16, 22.34, 21.72, 22.04, 21.26, 20.92, 20.09, 20.22, 19.66, 19.11, 21.44, 22.97, 22.38, 19.8, 21.0, 21.05, 17.92, 20.74, 19.67, 19.78, 21.46, 22.43, 20.82, 19.77, 20.58, 19.02, 15.3, 21.54, 20.58, 20.36, 20.61, 21.65, 19.49)
(7, '65 and Older', 20.82, 20.42, 16.59, 25.07, 20.66, 21.55, 17.93, 22.73, 25.73, 11.64, 27.76, 19.12, 24.05, 18.57, 20.28, 18.63, 19.95, 19.49, 18.6, 19.6, 22.84, 20.99, 21.27, 20.57, 19.87, 20.51, 19.68, 21.22, 19.17, 22.99, 20.83, 21.81, 25.66, 21.45, 20.82, 18.33, 19.96, 20.0, 21.98, 22.09, 22.31, 22.09, 20.21, 19.52, 17.76, 13.17, 21.72, 19.73, 20.26, 21.56, 20.59, 24.08)

In [357]:
conn.commit()
conn.close()